// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Chat struct {
	ID        int64
	Command   string
	Step      int16
	Data      []byte
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Product struct {
	ID        int32
	Name      string
	Label     string
	Category  string
	Uri       string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type ProductVersion struct {
	ID                 int32
	ProductID          int32
	ReleaseName        string
	ReleaseCodename    *string
	ReleaseLabel       string
	ReleaseDate        pgtype.Timestamp
	Version            *string
	VersionReleaseDate pgtype.Timestamp
	VersionReleaseLink *string
	CreatedAt          pgtype.Timestamp
}

type User struct {
	ID        int64
	Username  *string
	FirstName *string
	LastName  *string
	CreatedAt pgtype.Timestamp
}

type WatchList struct {
	ID        int32
	ChatID    int64
	ProductID int32
	CreatedAt pgtype.Timestamp
}
