/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Chat {
  command: string;
  created_at: Timestamp;
  data: Json | null;
  id: Int8;
  step: number;
  updated_at: Timestamp | null;
}

export interface Product {
  created_at: Timestamp;
  id: Generated<Int8>;
  name: string;
  sha: string | null;
  size: Int8 | null;
  updated_at: Timestamp | null;
  url: string;
}

export interface ProductVersion {
  created_at: Timestamp;
  id: Generated<Int8>;
  product_id: Int8;
  release_date: Timestamp;
  updated_at: Timestamp | null;
  version: string;
}

export interface User {
  created_at: Timestamp;
  first_name: string | null;
  id: Int8;
  last_name: string | null;
  username: string | null;
}

export interface WatchList {
  chat_id: Int8;
  created_at: Timestamp;
  id: Generated<Int8>;
  product_id: Int8;
  updated_at: Timestamp | null;
}

export interface DB {
  chat: Chat;
  product: Product;
  product_version: ProductVersion;
  user: User;
  watch_list: WatchList;
}
